<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ExamSchedulesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $examSchedules = [
            [
                'semester_id' => 1,
                'academic_level' => 1,
                'specialization' => null,
                'subject_name' => 'الجبر العام',
                'day' => 'الأحد',
                'date' => '2025/02/02',
                'start_time' => '11:30',
                'end_time' => '13:30',
                'status' => true,
            ],

            [
                'semester_id' => 1,
                'academic_level' => 1,
                'specialization' => null,
                'subject_name' => 'تحليل 1',
                'day' => 'الاثنين',
                'date' => '2025/02/10',
                'start_time' => '11:30',
                'end_time' => '13:30',
                'status' => true,
            ],

            [
                'semester_id' => 1,
                'academic_level' => 1,
                'specialization' => null,
                'subject_name' => 'اللغة الإنكليزية 1',
                'day' => 'الأربعاء',
                'date' => '2025/02/12',
                'start_time' => '11:30',
                'end_time' => '13:30',
                'status' => true,
            ],

            [
                'semester_id' => 1,
                'academic_level' => 1,
                'specialization' => null,
                'subject_name' => 'مبادئ عمل الحاسب',
                'day' => 'الأحد',
                'date' => '2025/02/23',
                'start_time' => '09:00',
                'end_time' => '11:00',
                'status' => true,
            ],

            [
                'semester_id' => 1,
                'academic_level' => 1,
                'specialization' => null,
                'subject_name' => 'الفيزياء',
                'day' => 'الخميس',
                'date' => '2025/02/27',
                'start_time' => '09:00',
                'end_time' => '11:00',
                'status' => true,
            ],

            [
                'semester_id' => 1,
                'academic_level' => 1,
                'specialization' => null,
                'subject_name' => 'برمجة 1',
                'day' => 'الخميس',
                'date' => '2025/03/06',
                'start_time' => '09:00',
                'end_time' => '11:00',
                'status' => true,
            ],

            [
                'semester_id' => 1,
                'academic_level' => 1,
                'specialization' => null,
                'subject_name' => 'الدارات الكهربائية والإلكترونية',
                'day' => 'الثلاثاء',
                'date' => '2025/02/04',
                'start_time' => '11:30',
                'end_time' => '13:30',
                'status' => false,
            ],

            [
                'semester_id' => 1,
                'academic_level' => 1,
                'specialization' => null,
                'subject_name' => 'تحليل 2',
                'day' => 'الخميس',
                'date' => '2025/02/06',
                'start_time' => '09:00',
                'end_time' => '11:00',
                'status' => false,
            ],

            [
                'semester_id' => 1,
                'academic_level' => 1,
                'specialization' => null,
                'subject_name' => 'اللغة العربية',
                'day' => 'الأحد',
                'date' => '2025/02/16',
                'start_time' => '11:30',
                'end_time' => '13:30',
                'status' => false,
            ],

            [
                'semester_id' => 1,
                'academic_level' => 1,
                'specialization' => null,
                'subject_name' => 'الجبر الخطي',
                'day' => 'الثلاثاء',
                'date' => '2025/02/18',
                'start_time' => '09:00',
                'end_time' => '11:00',
                'status' => false,
            ],

            [
                'semester_id' => 1,
                'academic_level' => 1,
                'specialization' => null,
                'subject_name' => 'اللغة الإنكليزية 2',
                'day' => 'الأربعاء',
                'date' => '2025/02/19',
                'start_time' => '11:30',
                'end_time' => '13:30',
                'status' => false,
            ],

            [
                'semester_id' => 1,
                'academic_level' => 1,
                'specialization' => null,
                'subject_name' => 'الثقافة القومية الاشتراكية',
                'day' => 'الأربعاء',
                'date' => '2025/02/26',
                'start_time' => '09:00',
                'end_time' => '11:00',
                'status' => false,
            ],
            [
                'semester_id' => 1,
                'academic_level' => 1,
                'specialization' => null,
                'subject_name' => 'برمجة 2',
                'day' => 'الاثنين',
                'date' => '2025/03/03',
                'start_time' => '09:00',
                'end_time' => '11:00',
                'status' => false,
            ],
            // السنة الثانية
            [
                'semester_id' => 1,
                'academic_level' => 2,
                'specialization' => null,
                'subject_name' => 'تحليل 3',
                'day' => 'الاثنين',
                'date' => '2025/02/03',
                'start_time' => '09:00',
                'end_time' => '11:00',
                'status' => true,
            ],
            [
                'semester_id' => 1,
                'academic_level' => 2,
                'specialization' => null,
                'subject_name' => 'الخوارزميات وبنى المعطيات 1',
                'day' => 'الأحد',
                'date' => '2025/02/09',
                'start_time' => '09:00',
                'end_time' => '11:00',
                'status' => true,
            ],
            [
                'semester_id' => 1,
                'academic_level' => 2,
                'specialization' => null,
                'subject_name' => 'برمجة 3',
                'day' => 'الأحد',
                'date' => '2025/02/16',
                'start_time' => '09:00',
                'end_time' => '11:00',
                'status' => true,
            ],
            [
                'semester_id' => 1,
                'academic_level' => 2,
                'specialization' => null,
                'subject_name' => 'اللغة الإنكليزية 3',
                'day' => 'الخميس',
                'date' => '2025/02/20',
                'start_time' => '11:30',
                'end_time' => '13:30',
                'status' => true,
            ],
            [
                'semester_id' => 1,
                'academic_level' => 2,
                'specialization' => null,
                'subject_name' => 'الدارات المنطقية',
                'day' => 'الاثنين',
                'date' => '2025/02/24',
                'start_time' => '09:00',
                'end_time' => '11:00',
                'status' => true,
            ],
            [
                'semester_id' => 1,
                'academic_level' => 2,
                'specialization' => null,
                'subject_name' => 'الاحتمالات والإحصاء',
                'day' => 'الثلاثاء',
                'date' => '2025/03/04',
                'start_time' => '09:00',
                'end_time' => '11:00',
                'status' => true,
            ],
            [
                'semester_id' => 1,
                'academic_level' => 2,
                'specialization' => null,
                'subject_name' => 'الاتصالات الرقمية ونظرية المعلومات',
                'day' => 'الأحد',
                'date' => '2025/02/02',
                'start_time' => '09:00',
                'end_time' => '11:00',
                'status' => false,
            ],
            [
                'semester_id' => 1,
                'academic_level' => 2,
                'specialization' => null,
                'subject_name' => 'مهارات تواصل',
                'day' => 'الثلاثاء',
                'date' => '2025/02/11',
                'start_time' => '14:00',
                'end_time' => '16:00',
                'status' => false,
            ],
            [
                'semester_id' => 1,
                'academic_level' => 2,
                'specialization' => null,
                'subject_name' => 'بنيان الحواسيب 1',
                'day' => 'الخميس',
                'date' => '2025/02/13',
                'start_time' => '09:00',
                'end_time' => '11:00',
                'status' => false,
            ],
            [
                'semester_id' => 1,
                'academic_level' => 2,
                'specialization' => null,
                'subject_name' => 'التحليل العددي',
                'day' => 'الاثنين',
                'date' => '2025/02/17',
                'start_time' => '09:00',
                'end_time' => '11:00',
                'status' => false,
            ],
            [
                'semester_id' => 1,
                'academic_level' => 2,
                'specialization' => null,
                'subject_name' => 'اللغة الإنكليزية 4',
                'day' => 'الثلاثاء',
                'date' => '2025/02/25',
                'start_time' => '11:30',
                'end_time' => '13:30',
                'status' => false,
            ],
            [
                'semester_id' => 1,
                'academic_level' => 2,
                'specialization' => null,
                'subject_name' => 'الخوارزميات وبنى المعطيات 2',
                'day' => 'الأحد',
                'date' => '2025/03/02',
                'start_time' => '09:00',
                'end_time' => '11:00',
                'status' => false,
            ],
            // السنة الثالثة - فصل أول
            [
                'semester_id' => 1,
                'academic_level' => 3,
                'specialization' => null,
                'subject_name' => 'بحوث عمليات',
                'day' => 'الثلاثاء',
                'date' => '2025/02/04',
                'start_time' => '09:00',
                'end_time' => '11:00',
                'status' => true,
            ],
            [
                'semester_id' => 1,
                'academic_level' => 3,
                'specialization' => null,
                'subject_name' => 'بيانيات حاسوبية',
                'day' => 'الثلاثاء',
                'date' => '2025/02/11',
                'start_time' => '09:00',
                'end_time' => '11:00',
                'status' => true,
            ],
            [
                'semester_id' => 1,
                'academic_level' => 3,
                'specialization' => null,
                'subject_name' => 'بنيان الحواسيب 2',
                'day' => 'الأربعاء',
                'date' => '2025/02/19',
                'start_time' => '11:30',
                'end_time' => '13:30',
                'status' => true,
            ],
            [
                'semester_id' => 1,
                'academic_level' => 3,
                'specialization' => null,
                'subject_name' => 'أساسيات الشبكات الحاسوبية',
                'day' => 'الخميس',
                'date' => '2025/02/27',
                'start_time' => '11:30',
                'end_time' => '13:30',
                'status' => true,
            ],
            [
                'semester_id' => 1,
                'academic_level' => 3,
                'specialization' => null,
                'subject_name' => 'لغات البرمجة',
                'day' => 'الأربعاء',
                'date' => '2025/03/05',
                'start_time' => '11:30',
                'end_time' => '13:30',
                'status' => true,
            ],

            // السنة الثالثة - فصل ثاني
            [
                'semester_id' => 1,
                'academic_level' => 3,
                'specialization' => null,
                'subject_name' => 'مشروع 1',
                'day' => 'الأربعاء',
                'date' => '2025/02/05',
                'start_time' => '14:00',
                'end_time' => '16:00',
                'status' => false,
            ],
            [
                'semester_id' => 1,
                'academic_level' => 3,
                'specialization' => null,
                'subject_name' => 'مبادئ الذكاء الصنعي',
                'day' => 'الخميس',
                'date' => '2025/02/06',
                'start_time' => '11:30',
                'end_time' => '13:30',
                'status' => false,
            ],
            [
                'semester_id' => 1,
                'academic_level' => 3,
                'specialization' => null,
                'subject_name' => 'حسابات علمية',
                'day' => 'الأربعاء',
                'date' => '2025/02/11',
                'start_time' => '14:00',
                'end_time' => '16:00',
                'status' => false,
            ],
            [
                'semester_id' => 1,
                'academic_level' => 3,
                'specialization' => null,
                'subject_name' => 'اللغات الصورية',
                'day' => 'الأحد',
                'date' => '2025/02/23',
                'start_time' => '11:30',
                'end_time' => '13:30',
                'status' => false,
            ],
            [
                'semester_id' => 1,
                'academic_level' => 3,
                'specialization' => null,
                'subject_name' => 'قواعد المعطيات 1',
                'day' => 'الأربعاء',
                'date' => '2025/02/26',
                'start_time' => '09:00',
                'end_time' => '11:00',
                'status' => false,
            ],
            // السنة الرابعة - برمجيات - فصل أول
            [
                'semester_id' => 1,
                'academic_level' => 4,
                'specialization' => 1,
                'subject_name' => 'هندسة البرمجيات 1',
                'day' => 'الأربعاء',
                'date' => '2025/02/05',
                'start_time' => '09:00',
                'end_time' => '11:00',
                'status' => true,
            ],
            [
                'semester_id' => 1,
                'academic_level' => 4,
                'specialization' => 1,
                'subject_name' => 'الاقتصاد والإدارة في المؤسسة',
                'day' => 'الاثنين',
                'date' => '2025/02/10',
                'start_time' => '11:30',
                'end_time' => '13:30',
                'status' => true,
            ],
            [
                'semester_id' => 1,
                'academic_level' => 4,
                'specialization' => 1,
                'subject_name' => 'قواعد المعطيات 2',
                'day' => 'الاثنين',
                'date' => '2025/02/17',
                'start_time' => '11:30',
                'end_time' => '13:30',
                'status' => true,
            ],
            [
                'semester_id' => 1,
                'academic_level' => 4,
                'specialization' => 1,
                'subject_name' => 'نظم التشغيل 1',
                'day' => 'الخميس',
                'date' => '2025/02/20',
                'start_time' => '09:00',
                'end_time' => '11:00',
                'status' => true,
            ],
            [
                'semester_id' => 1,
                'academic_level' => 4,
                'specialization' => 1,
                'subject_name' => 'المترجمات',
                'day' => 'الثلاثاء',
                'date' => '2025/02/25',
                'start_time' => '09:00',
                'end_time' => '11:00',
                'status' => true,
            ],
            [
                'semester_id' => 1,
                'academic_level' => 4,
                'specialization' => 1,
                'subject_name' => 'خوارزميات البحث الذكية',
                'day' => 'الخميس',
                'date' => '2025/03/06',
                'start_time' => '11:30',
                'end_time' => '13:30',
                'status' => true,
            ],

            // السنة الرابعة - برمجيات - فصل ثاني
            [
                'semester_id' => 1,
                'academic_level' => 4,
                'specialization' => 1,
                'subject_name' => 'مشروع مترجمات',
                'day' => 'الاثنين',
                'date' => '2025/02/03',
                'start_time' => '14:00',
                'end_time' => '16:00',
                'status' => false,
            ],
            [
                'semester_id' => 1,
                'academic_level' => 4,
                'specialization' => 1,
                'subject_name' => 'مشروع 2',
                'day' => 'الخميس',
                'date' => '2025/02/06',
                'start_time' => '14:00',
                'end_time' => '16:00',
                'status' => false,
            ],
            [
                'semester_id' => 1,
                'academic_level' => 4,
                'specialization' => 1,
                'subject_name' => 'نظم وسائط متعددة وفائقة',
                'day' => 'الأربعاء',
                'date' => '2025/02/19',
                'start_time' => '09:00',
                'end_time' => '11:00',
                'status' => false,
            ],
            [
                'semester_id' => 1,
                'academic_level' => 4,
                'specialization' => 1,
                'subject_name' => 'البرمجة التفرعية',
                'day' => 'الاثنين',
                'date' => '2025/02/24',
                'start_time' => '11:30',
                'end_time' => '13:30',
                'status' => false,
            ],
            [
                'semester_id' => 1,
                'academic_level' => 4,
                'specialization' => 1,
                'subject_name' => 'هندسة البرمجيات 2',
                'day' => 'الأحد',
                'date' => '2025/03/02',
                'start_time' => '11:30',
                'end_time' => '13:30',
                'status' => false,
            ],
            [
                'semester_id' => 1,
                'academic_level' => 4,
                'specialization' => 1,
                'subject_name' => 'تسويق',
                'day' => 'الثلاثاء',
                'date' => '2025/03/04',
                'start_time' => '11:30',
                'end_time' => '13:30',
                'status' => false,
            ],
            // السنة الرابعة - ذكاء اصطناعي - فصل أول
            [
                'semester_id' => 1,
                'academic_level' => 4,
                'specialization' => 2,
                'subject_name' => 'هندسة البرمجيات 1',
                'day' => 'الأربعاء',
                'date' => '2025/02/05',
                'start_time' => '09:00',
                'end_time' => '11:00',
                'status' => true,
            ],
            [
                'semester_id' => 1,
                'academic_level' => 4,
                'specialization' => 2,
                'subject_name' => 'الاقتصاد والإدارة في المؤسسة',
                'day' => 'الاثنين',
                'date' => '2025/02/10',
                'start_time' => '11:30',
                'end_time' => '13:30',
                'status' => true,
            ],
            [
                'semester_id' => 1,
                'academic_level' => 4,
                'specialization' => 2,
                'subject_name' => 'المترجمات',
                'day' => 'الأحد',
                'date' => '2025/02/16',
                'start_time' => '09:00',
                'end_time' => '11:00',
                'status' => true,
            ],
            [
                'semester_id' => 1,
                'academic_level' => 4,
                'specialization' => 2,
                'subject_name' => 'نظم التشغيل 1',
                'day' => 'الخميس',
                'date' => '2025/02/20',
                'start_time' => '09:00',
                'end_time' => '11:00',
                'status' => true,
            ],
            [
                'semester_id' => 1,
                'academic_level' => 4,
                'specialization' => 2,
                'subject_name' => 'الشبكات العصبونية',
                'day' => 'الثلاثاء',
                'date' => '2025/02/25',
                'start_time' => '09:00',
                'end_time' => '11:00',
                'status' => true,
            ],
            [
                'semester_id' => 1,
                'academic_level' => 4,
                'specialization' => 2,
                'subject_name' => 'خوارزميات البحث الذكية',
                'day' => 'الخميس',
                'date' => '2025/03/06',
                'start_time' => '11:30',
                'end_time' => '13:30',
                'status' => true,
            ],

            // السنة الرابعة - ذكاء اصطناعي - فصل ثاني
            [
                'semester_id' => 1,
                'academic_level' => 4,
                'specialization' => 2,
                'subject_name' => 'مشروع 2',
                'day' => 'الخميس',
                'date' => '2025/02/06',
                'start_time' => '14:00',
                'end_time' => '16:00',
                'status' => false,
            ],
            [
                'semester_id' => 1,
                'academic_level' => 4,
                'specialization' => 2,
                'subject_name' => 'الحائق الأفتراضية',
                'day' => 'الأربعاء',
                'date' => '2025/02/17',
                'start_time' => '09:00',
                'end_time' => '11:00',
                'status' => false,
            ],
            [
                'semester_id' => 1,
                'academic_level' => 4,
                'specialization' => 2,
                'subject_name' => 'نظم وسائط متعددة وفائقة',
                'day' => 'الأربعاء',
                'date' => '2025/02/19',
                'start_time' => '09:00',
                'end_time' => '11:00',
                'status' => false,
            ],
            [
                'semester_id' => 1,
                'academic_level' => 4,
                'specialization' => 2,
                'subject_name' => 'البرمجة التفرعية',
                'day' => 'الاثنين',
                'date' => '2025/02/24',
                'start_time' => '11:30',
                'end_time' => '13:30',
                'status' => false,
            ],
            [
                'semester_id' => 1,
                'academic_level' => 4,
                'specialization' => 2,
                'subject_name' => 'نظم قواعد المعرفة',
                'day' => 'الأحد',
                'date' => '2025/03/02',
                'start_time' => '11:30',
                'end_time' => '13:30',
                'status' => false,
            ],
            [
                'semester_id' => 1,
                'academic_level' => 4,
                'specialization' => 2,
                'subject_name' => 'تسويق',
                'day' => 'الثلاثاء',
                'date' => '2025/03/04',
                'start_time' => '11:30',
                'end_time' => '13:30',
                'status' => false,
            ],
            // السنة الرابعة - شبكات - فصل أول
            [
                'semester_id' => 1,
                'academic_level' => 4,
                'specialization' => 3,
                'subject_name' => 'هندسة البرمجيات 1',
                'day' => 'الأربعاء',
                'date' => '2025/02/05',
                'start_time' => '09:00',
                'end_time' => '11:00',
                'status' => true,
            ],
            [
                'semester_id' => 1,
                'academic_level' => 4,
                'specialization' => 3,
                'subject_name' => 'الاقتصاد والإدارة في المؤسسة',
                'day' => 'الاثنين',
                'date' => '2025/02/10',
                'start_time' => '11:30',
                'end_time' => '13:30',
                'status' => true,
            ],
            [
                'semester_id' => 1,
                'academic_level' => 4,
                'specialization' => 3,
                'subject_name' => 'نظم التشغيل 1',
                'day' => 'الخميس',
                'date' => '2025/02/20',
                'start_time' => '09:00',
                'end_time' => '11:00',
                'status' => true,
            ],
            [
                'semester_id' => 1,
                'academic_level' => 4,
                'specialization' => 3,
                'subject_name' => 'برمجة التطبيقات الشبكية',
                'day' => 'الأربعاء',
                'date' => '2025/02/26',
                'start_time' => '11:30',
                'end_time' => '13:30',
                'status' => true,
            ],
            [
                'semester_id' => 1,
                'academic_level' => 4,
                'specialization' => 3,
                'subject_name' => 'خوارزميات البحث الذكية',
                'day' => 'الخميس',
                'date' => '2025/03/06',
                'start_time' => '11:30',
                'end_time' => '13:30',
                'status' => true,
            ],

            // السنة الرابعة - شبكات - فصل ثاني
            [
                'semester_id' => 1,
                'academic_level' => 4,
                'specialization' => 3,
                'subject_name' => 'مشروع 2',
                'day' => 'الخميس',
                'date' => '2025/02/06',
                'start_time' => '14:00',
                'end_time' => '16:00',
                'status' => false,
            ],
            [
                'semester_id' => 1,
                'academic_level' => 4,
                'specialization' => 3,
                'subject_name' => 'بروتوكولات الاتصال الحاسوبية',
                'day' => 'الاثنين',
                'date' => '2025/02/17',
                'start_time' => '14:00',
                'end_time' => '16:00',
                'status' => false,
            ],
            [
                'semester_id' => 1,
                'academic_level' => 4,
                'specialization' => 3,
                'subject_name' => 'نظم وسائط متعددة وفائقة',
                'day' => 'الأربعاء',
                'date' => '2025/02/19',
                'start_time' => '09:00',
                'end_time' => '11:00',
                'status' => false,
            ],
            [
                'semester_id' => 1,
                'academic_level' => 4,
                'specialization' => 3,
                'subject_name' => 'البرمجة التفرعية',
                'day' => 'الاثنين',
                'date' => '2025/02/24',
                'start_time' => '11:30',
                'end_time' => '13:30',
                'status' => false,
            ],
            [
                'semester_id' => 1,
                'academic_level' => 4,
                'specialization' => 3,
                'subject_name' => 'نظم تشغيل 2',
                'day' => 'الأحد',
                'date' => '2025/03/02',
                'start_time' => '11:30',
                'end_time' => '13:30',
                'status' => false,
            ],
            [
                'semester_id' => 1,
                'academic_level' => 4,
                'specialization' => 3,
                'subject_name' => 'تسويق',
                'day' => 'الثلاثاء',
                'date' => '2025/03/04',
                'start_time' => '11:30',
                'end_time' => '13:30',
                'status' => false,
            ],
            // السنة الخامسة - برمجيات - فصل أول
            [
                'semester_id' => 1,
                'academic_level' => 5,
                'specialization' => 1,
                'subject_name' => 'مشروع تخرج',
                'day' => 'الأحد',
                'date' => '2025/02/02',
                'start_time' => '14:00',
                'end_time' => '16:00',
                'status' => true,
            ],
            [
                'semester_id' => 1,
                'academic_level' => 5,
                'specialization' => 1,
                'subject_name' => 'هندسة برمجيات 3',
                'day' => 'الاثنين',
                'date' => '2025/02/03',
                'start_time' => '11:30',
                'end_time' => '13:30',
                'status' => true,
            ],
            [
                'semester_id' => 1,
                'academic_level' => 5,
                'specialization' => 1,
                'subject_name' => 'قواعد معطيات متقدمة',
                'day' => 'الثلاثاء',
                'date' => '2025/02/11',
                'start_time' => '11:30',
                'end_time' => '13:30',
                'status' => true,
            ],
            [
                'semester_id' => 1,
                'academic_level' => 5,
                'specialization' => 1,
                'subject_name' => 'إدارة المشاريع',
                'day' => 'الثلاثاء',
                'date' => '2025/02/18',
                'start_time' => '11:30',
                'end_time' => '13:30',
                'status' => true,
            ],
            [
                'semester_id' => 1,
                'academic_level' => 5,
                'specialization' => 1,
                'subject_name' => 'تطبيقات الإنترنت',
                'day' => 'الأربعاء',
                'date' => '2025/02/26',
                'start_time' => '11:30',
                'end_time' => '13:30',
                'status' => true,
            ],
            [
                'semester_id' => 1,
                'academic_level' => 5,
                'specialization' => 1,
                'subject_name' => 'أمن نظم المعلومات',
                'day' => 'الأربعاء',
                'date' => '2025/03/05',
                'start_time' => '09:00',
                'end_time' => '11:00',
                'status' => true,
            ],

            // السنة الخامسة - برمجيات - فصل ثاني
            [
                'semester_id' => 1,
                'academic_level' => 5,
                'specialization' => 1,
                'subject_name' => 'النظم والتطبيقات الموزعة',
                'day' => 'الأحد',
                'date' => '2025/02/09',
                'start_time' => '11:30',
                'end_time' => '13:30',
                'status' => false,
            ],
            [
                'semester_id' => 1,
                'academic_level' => 5,
                'specialization' => 1,
                'subject_name' => 'نظم البحث عن المعلومات',
                'day' => 'الخميس',
                'date' => '2025/02/13',
                'start_time' => '11:30',
                'end_time' => '13:30',
                'status' => false,
            ],
            [
                'semester_id' => 1,
                'academic_level' => 5,
                'specialization' => 1,
                'subject_name' => 'هندسة نظم المعلومات',
                'day' => 'الاثنين',
                'date' => '2025/03/03',
                'start_time' => '11:30',
                'end_time' => '13:30',
                'status' => false,
            ],
            // السنة الخامسة - ذكاء اصطناعي - فصل أول
            [
                'semester_id' => 1,
                'academic_level' => 5,
                'specialization' => 2,
                'subject_name' => 'مشروع تخرج',
                'day' => 'الأحد',
                'date' => '2025/02/02',
                'start_time' => '14:00',
                'end_time' => '16:00',
                'status' => true,
            ],
            [
                'semester_id' => 1,
                'academic_level' => 5,
                'specialization' => 2,
                'subject_name' => 'الروبوتية',
                'day' => 'الاثنين',
                'date' => '2025/02/03',
                'start_time' => '11:30',
                'end_time' => '13:30',
                'status' => true,
            ],
            [
                'semester_id' => 1,
                'academic_level' => 5,
                'specialization' => 2,
                'subject_name' => 'الرؤية الحاسوبية',
                'day' => 'الثلاثاء',
                'date' => '2025/02/11',
                'start_time' => '11:30',
                'end_time' => '13:30',
                'status' => true,
            ],
            [
                'semester_id' => 1,
                'academic_level' => 5,
                'specialization' => 2,
                'subject_name' => 'إدارة المشاريع',
                'day' => 'الثلاثاء',
                'date' => '2025/02/18',
                'start_time' => '11:30',
                'end_time' => '13:30',
                'status' => true,
            ],
            [
                'semester_id' => 1,
                'academic_level' => 5,
                'specialization' => 2,
                'subject_name' => 'معالجة اللغات الطبيعية',
                'day' => 'الأربعاء',
                'date' => '2025/02/26',
                'start_time' => '11:30',
                'end_time' => '13:30',
                'status' => true,
            ],
            [
                'semester_id' => 1,
                'academic_level' => 5,
                'specialization' => 2,
                'subject_name' => 'أمن نظم المعلومات',
                'day' => 'الأربعاء',
                'date' => '2025/03/05',
                'start_time' => '09:00',
                'end_time' => '11:00',
                'status' => true,
            ],

            // السنة الخامسة - ذكاء اصطناعي - فصل ثاني
            [
                'semester_id' => 1,
                'academic_level' => 5,
                'specialization' => 2,
                'subject_name' => 'المنطق الترجيحي والخوارزميات الوراثية',
                'day' => 'الأحد',
                'date' => '2025/02/09',
                'start_time' => '11:30',
                'end_time' => '13:30',
                'status' => false,
            ],
            [
                'semester_id' => 1,
                'academic_level' => 5,
                'specialization' => 2,
                'subject_name' => 'استكشاف المعرفة',
                'day' => 'الخميس',
                'date' => '2025/02/13',
                'start_time' => '11:30',
                'end_time' => '13:30',
                'status' => false,
            ],
            [
                'semester_id' => 1,
                'academic_level' => 5,
                'specialization' => 2,
                'subject_name' => 'التعلم التلقائي',
                'day' => 'الاثنين',
                'date' => '2025/03/03',
                'start_time' => '11:30',
                'end_time' => '13:30',
                'status' => false,
            ],
            // السنة الخامسة - شبكات - فصل أول
            [
                'semester_id' => 1,
                'academic_level' => 5,
                'specialization' => 3,
                'subject_name' => 'مشروع تخرج',
                'day' => 'الأحد',
                'date' => '2025/02/02',
                'start_time' => '14:00',
                'end_time' => '16:00',
                'status' => true,
            ],
            [
                'semester_id' => 1,
                'academic_level' => 5,
                'specialization' => 3,
                'subject_name' => 'نظم التطبيقات الموزعة',
                'day' => 'الاثنين',
                'date' => '2025/02/03',
                'start_time' => '11:30',
                'end_time' => '13:30',
                'status' => true,
            ],
            [
                'semester_id' => 1,
                'academic_level' => 5,
                'specialization' => 3,
                'subject_name' => 'إدارة الشبكات الحاسوبية',
                'day' => 'الثلاثاء',
                'date' => '2025/02/11',
                'start_time' => '11:30',
                'end_time' => '13:30',
                'status' => true,
            ],
            [
                'semester_id' => 1,
                'academic_level' => 5,
                'specialization' => 3,
                'subject_name' => 'إدارة المشاريع',
                'day' => 'الثلاثاء',
                'date' => '2025/02/18',
                'start_time' => '11:30',
                'end_time' => '13:30',
                'status' => true,
            ],
            [
                'semester_id' => 1,
                'academic_level' => 5,
                'specialization' => 3,
                'subject_name' => 'تصميم الشبكات الحاسوبية',
                'day' => 'الثلاثاء',
                'date' => '2025/02/25',
                'start_time' => '11:30',
                'end_time' => '13:30',
                'status' => true,
            ],
            [
                'semester_id' => 1,
                'academic_level' => 5,
                'specialization' => 3,
                'subject_name' => 'أمن نظم المعلومات',
                'day' => 'الأربعاء',
                'date' => '2025/03/05',
                'start_time' => '09:00',
                'end_time' => '11:00',
                'status' => true,
            ],

            // السنة الخامسة - شبكات - فصل ثاني
            [
                'semester_id' => 1,
                'academic_level' => 5,
                'specialization' => 3,
                'subject_name' => 'أمن الشبكات الحاسوبية',
                'day' => 'الأحد',
                'date' => '2025/02/09',
                'start_time' => '11:30',
                'end_time' => '13:30',
                'status' => false,
            ],
            [
                'semester_id' => 1,
                'academic_level' => 5,
                'specialization' => 3,
                'subject_name' => 'نمذجة ومحاكاة النظم الشبكية',
                'day' => 'الخميس',
                'date' => '2025/02/13',
                'start_time' => '11:30',
                'end_time' => '13:30',
                'status' => false,
            ],
            [
                'semester_id' => 1,
                'academic_level' => 5,
                'specialization' => 3,
                'subject_name' => 'نظم الزمن الحقيقي',
                'day' => 'الاثنين',
                'date' => '2025/03/03',
                'start_time' => '11:30',
                'end_time' => '13:30',
                'status' => false,
            ],

        ];
        DB::table('exam_schedules')->insert($examSchedules);
    }
}
