<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class WorkScheduleSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('work_schedules')->insert([
            [
                // // الاحد
                'semester_id' => 2,
                'academic_level' => 1,
                'specialization' => null,
                'course_name' => 'عملي تحليل 2',
                'instructor_name' => 'ق.أ. مهند بكر - م. هيام نجم الدين',
                'day' => 'الأحد',
                'start_time' => '08:30:00',
                'end_time' => '10:30:00',
                'room' => 'مدرج 22',
                'branch' => '1',
            ],
            [
                'semester_id' => 2,
                'academic_level' => 1,
                'specialization' => null,
                'course_name' => 'عملي جبر خطي',
                'instructor_name' => 'م. شذا الخطيب - م. عبير الكجك',
                'day' => 'الأحد',
                'start_time' => '12:30:00',
                'end_time' => '02:30:00',
                'room' => 'مدرج 22',
                'branch' => '1',
            ],
            [
                'semester_id' => 2,
                'academic_level' => 1,
                'specialization' => null,
                'course_name' => 'عملي جبر خطي',
                'instructor_name' => 'م. شذا الخطيب - م. عبير الكجك',
                'day' => 'الأحد',
                'start_time' => '08:30:00',
                'end_time' => '10:30:00',
                'room' => 'مدرج 21',
                'branch' => '2',
            ],
            [
                'semester_id' => 2,
                'academic_level' => 1,
                'specialization' => null,
                'course_name' => 'عملي تحليل 2',
                'instructor_name' => 'ق.أ. مهند بكر - م. هيام نجم الدين',
                'day' => 'الأحد',
                'start_time' => '10:30:00',
                'end_time' => '12:30:00',
                'room' => 'مدرج 22',
                'branch' => '2',
            ],
            [
                'semester_id' => 2,
                'academic_level' => 1,
                'specialization' => null,
                'course_name' => 'برمجة 2',
                'instructor_name' => 'د. عبد الرحمن اللحام',
                'day' => 'الأحد',
                'start_time' => '08:30:00',
                'end_time' => '10:30:00',
                'room' => 'مدرج 1',
                'branch' => '3',
            ],
            [
                'semester_id' => 2,
                'academic_level' => 1,
                'specialization' => null,
                'course_name' => 'عملي جبر خطي',
                'instructor_name' => 'م. شذا الخطيب - م. عبير الكجك',
                'day' => 'الأحد',
                'start_time' => '10:30:00',
                'end_time' => '12:30:00',
                'room' => 'مدرج 21',
                'branch' => '3',
            ],
            [
                'semester_id' => 2,
                'academic_level' => 1,
                'specialization' => null,
                'course_name' => 'عملي تحليل 2',
                'instructor_name' => 'ق.أ. مهند بكر - م. هيام نجم الدين',
                'day' => 'الأحد',
                'start_time' => '12:30:00',
                'end_time' => '02:30:00',
                'room' => 'مدرج 22',
                'branch' => '3',
            ],
            // /// الاثنين
            [
                'semester_id' => 2,
                'academic_level' => 1,
                'specialization' => null,
                'course_name' => 'عملي برمجة 2',
                'instructor_name' => 'م.ميساء العبودي - م.مؤيد عالولا - م.عرين حسن - م. غالية صباغ',
                'day' => 'الاثنين',
                'start_time' => '08:30:00',
                'end_time' => '10:30:00',
                'room' => 'J1,K1,G1,H1',
                'branch' => '1',
            ],
            [
                'semester_id' => 2,
                'academic_level' => 1,
                'specialization' => null,
                'course_name' => ' جبر خطي',
                'instructor_name' => 'د.أسمهان خضور',
                'day' => 'الاثنين',
                'start_time' => '10:30:00',
                'end_time' => '12:30:00',
                'room' => 'مدرج 1',
                'branch' => '1',
            ],
            [
                'semester_id' => 2,
                'academic_level' => 1,
                'specialization' => null,
                'course_name' => 'تحليل 2',
                'instructor_name' => 'م.شذا الخطيب',
                'day' => 'الاثنين',
                'start_time' => '12:30:00',
                'end_time' => '02:30:00',
                'room' => 'مدرج 3',
                'branch' => '1',
            ],
            [
                'semester_id' => 2,
                'academic_level' => 1,
                'specialization' => null,
                'course_name' => 'تحليل 2',
                'instructor_name' => 'م.شذا الخطيب',
                'day' => 'الاثنين',
                'start_time' => '08:30:00',
                'end_time' => '10:30:00',
                'room' => 'مدرج 3',
                'branch' => '2',
            ],
            [
                'semester_id' => 2,
                'academic_level' => 1,
                'specialization' => null,
                'course_name' => 'عملي برمجة 2',
                'instructor_name' => 'م.ميساء العبودي - م.مؤيد عالولا - م.عرين حسن - م. غالية صباغ',
                'day' => 'الاثنين',
                'start_time' => '10:30:00',
                'end_time' => '12:30:00',
                'room' => 'J1,K1,G1,H1',
                'branch' => '2',
            ],
            [
                'semester_id' => 2,
                'academic_level' => 1,
                'specialization' => null,
                'course_name' => ' جبر خطي',
                'instructor_name' => 'د.أسمهان خضور',
                'day' => 'الاثنين',
                'start_time' => '12:30:00',
                'end_time' => '02:30:00',
                'room' => 'مدرج 1',
                'branch' => '2',
            ],
            [
                'semester_id' => 2,
                'academic_level' => 1,
                'specialization' => null,
                'course_name' => ' جبر خطي',
                'instructor_name' => 'د.أسمهان خضور',
                'day' => 'الاثنين',
                'start_time' => '08:30:00',
                'end_time' => '10:30:00',
                'room' => 'مدرج 1',
                'branch' => '3',
            ],
            [
                'semester_id' => 2,
                'academic_level' => 1,
                'specialization' => null,
                'course_name' => 'تحليل 2',
                'instructor_name' => 'م.شذا الخطيب',
                'day' => 'الاثنين',
                'start_time' => '10:30:00',
                'end_time' => '12:30:00',
                'room' => 'مدرج 3',
                'branch' => '3',
            ],
            [
                'semester_id' => 2,
                'academic_level' => 1,
                'specialization' => null,
                'course_name' => 'عملي برمجة 2',
                'instructor_name' => 'م.ميساء العبودي - م.مؤيد عالولا - م.عرين حسن - م. غالية صباغ',
                'day' => 'الاثنين',
                'start_time' => '12:30:00',
                'end_time' => '02:30:00',
                'room' => 'J1,K1,G1,H1',
                'branch' => '3',
            ],
            // // ثلاثاء
            [
                'semester_id' => 2,
                'academic_level' => 1,
                'specialization' => null,
                'course_name' => 'جبر خطي',
                'instructor_name' => 'د. اسمهان حضور',
                'day' => 'الثلاثاء',
                'start_time' => '02:30:00',
                'end_time' => '04:30:00',
                'room' => 'مدرج 1',
                'branch' => '1',
            ],
            [
                'semester_id' => 2,
                'academic_level' => 1,
                'specialization' => null,
                'course_name' => 'دارات كهربائية والكترونية',
                'instructor_name' => 'د. فاطمة الخضر',
                'day' => 'الثلاثاء',
                'start_time' => '08:30:00',
                'end_time' => '10:30:00',
                'room' => 'مدرج 3',
                'branch' => '2',
            ],
            [
                'semester_id' => 2,
                'academic_level' => 1,
                'specialization' => null,
                'course_name' => 'جبر خطي',
                'instructor_name' => 'د. اسمهان حضور',
                'day' => 'الثلاثاء',
                'start_time' => '10:30:00',
                'end_time' => '12:30:00',
                'room' => 'مدرج 3',
                'branch' => '2',
            ],
            [
                'semester_id' => 2,
                'academic_level' => 1,
                'specialization' => null,
                'course_name' => 'جبر خطي',
                'instructor_name' => 'د. اسمهان حضور',
                'day' => 'الثلاثاء',
                'start_time' => '09:30:00',
                'end_time' => '11:30:00',
                'room' => 'مدرج 1',
                'branch' => '3',
            ],
            [
                'semester_id' => 2,
                'academic_level' => 1,
                'specialization' => null,
                'course_name' => 'دارات كهربائية والكترونية',
                'instructor_name' => 'د. فاطمة الخضر',
                'day' => 'الثلاثاء',
                'start_time' => '11:30:00',
                'end_time' => '02:30:00',
                'room' => 'مدرج 3',
                'branch' => '3',
            ],
            // / لأربعاء
            [
                'semester_id' => 2,
                'academic_level' => 1,
                'specialization' => null,
                'course_name' => 'دارات كهربائية والكترونية',
                'instructor_name' => 'د. فاطمة الخضر',
                'day' => 'الأربعاء',
                'start_time' => '08:30:00',
                'end_time' => '11:30:00',
                'room' => 'مدرج 3',
                'branch' => '1',
            ],
            [
                'semester_id' => 2,
                'academic_level' => 1,
                'specialization' => null,
                'course_name' => 'برمجة 2',
                'instructor_name' => 'د. محمد الأحمد',
                'day' => 'الأربعاء',
                'start_time' => '11:30:00',
                'end_time' => '01:30:00',
                'room' => 'مدرج 1',
                'branch' => '1',
            ],
            [
                'semester_id' => 2,
                'academic_level' => 1,
                'specialization' => null,
                'course_name' => 'TD',
                'instructor_name' => 'ق.أ. ماهر صارم',
                'day' => 'الأربعاء',
                'start_time' => '01:30:00',
                'end_time' => '03:30:00',
                'room' => 'مدرج 21',
                'branch' => '1',
            ],
            [
                'semester_id' => 2,
                'academic_level' => 1,
                'specialization' => null,
                'course_name' => 'برمجة 2',
                'instructor_name' => 'د. محمد الأحمد',
                'day' => 'الأربعاء',
                'start_time' => '09:30:00',
                'end_time' => '11:30:00',
                'room' => 'مدرج 1',
                'branch' => '2',
            ],
            [
                'semester_id' => 2,
                'academic_level' => 1,
                'specialization' => null,
                'course_name' => 'TD',
                'instructor_name' => 'ق.أ. ماهر صارم',
                'day' => 'الأربعاء',
                'start_time' => '11:30:00',
                'end_time' => '01:30:00',
                'room' => 'مدرج 21',
                'branch' => '2',
            ],
            [
                'semester_id' => 2,
                'academic_level' => 1,
                'specialization' => null,
                'course_name' => 'TD',
                'instructor_name' => 'ق.أ. ماهر صارم',
                'day' => 'الأربعاء',
                'start_time' => '09:30:00',
                'end_time' => '11:30:00',
                'room' => 'مدرج 21',
                'branch' => '3',
            ],
            // // الخميس
            [
                'semester_id' => 2,
                'academic_level' => 1,
                'specialization' => null,
                'course_name' => 'عملي دارات كهربائية',
                'instructor_name' => 'م. فتون الشيخ أوغلي - م. هالة الرز',
                'day' => 'الخميس',
                'start_time' => '08:30:00',
                'end_time' => '10:30:00',
                'room' => 'مدرج 3-5',
                'branch' => '1',
            ],
            [
                'semester_id' => 2,
                'academic_level' => 1,
                'specialization' => null,
                'course_name' => 'عملي برمجة 2',
                'instructor_name' => 'م.ميساء العبودي - م.هبة كلو وانلي - م.نايف الصديق - م.كنان عبد الهادي ',
                'day' => 'الخميس',
                'start_time' => '10:30:00',
                'end_time' => '12:30:00',
                'room' => 'J1,K1,G1,H1',
                'branch' => '1',
            ],
            [
                'semester_id' => 2,
                'academic_level' => 1,
                'specialization' => null,
                'course_name' => 'تحليل 2',
                'instructor_name' => 'ق.أ. مهند بكر',
                'day' => 'الخميس',
                'start_time' => '12:30:00',
                'end_time' => '02:30:00',
                'room' => 'مدرج 21',
                'branch' => '1',
            ],
            [
                'semester_id' => 2,
                'academic_level' => 1,
                'specialization' => null,
                'course_name' => 'تحليل 2',
                'instructor_name' => 'ق.أ. مهند بكر',
                'day' => 'الخميس',
                'start_time' => '08:30:00',
                'end_time' => '10:30:00',
                'room' => 'مدرج 1',
                'branch' => '2',
            ],
            [
                'semester_id' => 2,
                'academic_level' => 1,
                'specialization' => null,
                'course_name' => 'عملي دارات كهربائية',
                'instructor_name' => 'م. فتون الشيخ أوغلي - م. هالة الرز',
                'day' => 'الخميس',
                'start_time' => '10:30:00',
                'end_time' => '12:30:00',
                'room' => 'مدرج 3-5',
                'branch' => '2',
            ],
            [
                'semester_id' => 2,
                'academic_level' => 1,
                'specialization' => null,
                'course_name' => 'عملي برمجة 2',
                'instructor_name' => 'م.ميساء العبودي - م.هبة كلو وانلي - م.نايف الصديق - م.كنان عبد الهادي ',
                'day' => 'الخميس',
                'start_time' => '12:30:00',
                'end_time' => '02:30:00',
                'room' => 'J1,K1,G1,H1',
                'branch' => '2',
            ],
            [
                'semester_id' => 2,
                'academic_level' => 1,
                'specialization' => null,
                'course_name' => 'عملي برمجة 2',
                'instructor_name' => 'م.ميساء العبودي - م.هبة كلو وانلي - م.نايف الصديق - م.كنان عبد الهادي ',
                'day' => 'الخميس',
                'start_time' => '08:30:00',
                'end_time' => '10:30:00',
                'room' => 'J1,K1,G1,H1',
                'branch' => '3',
            ],
            [
                'semester_id' => 2,
                'academic_level' => 1,
                'specialization' => null,
                'course_name' => 'تحليل 2',
                'instructor_name' => 'ق.أ. مهند بكر',
                'day' => 'الخميس',
                'start_time' => '10:30:00',
                'end_time' => '12:30:00',
                'room' => 'مدرج 1',
                'branch' => '3',
            ],
            [
                'semester_id' => 2,
                'academic_level' => 1,
                'specialization' => null,
                'course_name' => 'عملي دارات كهربائية',
                'instructor_name' => 'م. فتون الشيخ أوغلي - م. هالة الرز',
                'day' => 'الخميس',
                'start_time' => '12:30:00',
                'end_time' => '02:30:00',
                'room' => 'مدرج 3-5',
                'branch' => '3',
            ],

            // ///////////////////////////////////   222222222222222222222222
            [
                // // الاحد
                'semester_id' => 2,
                'academic_level' => 2,
                'specialization' => null,
                'course_name' => 'عملي تحليل 2',
                'instructor_name' => 'ق.أ. مهند بكر - م. هيام نجم الدين',
                'day' => 'الأحد',
                'start_time' => '08:30:00',
                'end_time' => '10:30:00',
                'room' => 'مدرج 22',
                'branch' => '1',
            ],
            [
                'semester_id' => 2,
                'academic_level' => 2,
                'specialization' => null,
                'course_name' => 'عملي جبر خطي',
                'instructor_name' => 'م. شذا الخطيب - م. عبير الكجك',
                'day' => 'الأحد',
                'start_time' => '12:30:00',
                'end_time' => '02:30:00',
                'room' => 'مدرج 22',
                'branch' => '1',
            ],
            [
                'semester_id' => 2,
                'academic_level' => 2,
                'specialization' => null,
                'course_name' => 'عملي جبر خطي',
                'instructor_name' => 'م. شذا الخطيب - م. عبير الكجك',
                'day' => 'الأحد',
                'start_time' => '08:30:00',
                'end_time' => '10:30:00',
                'room' => 'مدرج 21',
                'branch' => '2',
            ],
            [
                'semester_id' => 2,
                'academic_level' => 2,
                'specialization' => null,
                'course_name' => 'عملي تحليل 2',
                'instructor_name' => 'ق.أ. مهند بكر - م. هيام نجم الدين',
                'day' => 'الأحد',
                'start_time' => '10:30:00',
                'end_time' => '12:30:00',
                'room' => 'مدرج 22',
                'branch' => '2',
            ],
            [
                'semester_id' => 2,
                'academic_level' => 2,
                'specialization' => null,
                'course_name' => 'برمجة 2',
                'instructor_name' => 'د. عبد الرحمن اللحام',
                'day' => 'الأحد',
                'start_time' => '08:30:00',
                'end_time' => '10:30:00',
                'room' => 'مدرج 1',
                'branch' => '3',
            ],
            [
                'semester_id' => 2,
                'academic_level' => 2,
                'specialization' => null,
                'course_name' => 'عملي جبر خطي',
                'instructor_name' => 'م. شذا الخطيب - م. عبير الكجك',
                'day' => 'الأحد',
                'start_time' => '10:30:00',
                'end_time' => '12:30:00',
                'room' => 'مدرج 21',
                'branch' => '3',
            ],
            [
                'semester_id' => 2,
                'academic_level' => 2,
                'specialization' => null,
                'course_name' => 'عملي تحليل 2',
                'instructor_name' => 'ق.أ. مهند بكر - م. هيام نجم الدين',
                'day' => 'الأحد',
                'start_time' => '12:30:00',
                'end_time' => '02:30:00',
                'room' => 'مدرج 22',
                'branch' => '3',
            ],
            // /// الاثنين
            [
                'semester_id' => 2,
                'academic_level' => 2,
                'specialization' => null,
                'course_name' => 'عملي برمجة 2',
                'instructor_name' => 'م.ميساء العبودي - م.مؤيد عالولا - م.عرين حسن - م. غالية صباغ',
                'day' => 'الاثنين',
                'start_time' => '08:30:00',
                'end_time' => '10:30:00',
                'room' => 'J1,K1,G1,H1',
                'branch' => '1',
            ],
            [
                'semester_id' => 2,
                'academic_level' => 2,
                'specialization' => null,
                'course_name' => ' جبر خطي',
                'instructor_name' => 'د.أسمهان خضور',
                'day' => 'الاثنين',
                'start_time' => '10:30:00',
                'end_time' => '12:30:00',
                'room' => 'مدرج 1',
                'branch' => '1',
            ],
            [
                'semester_id' => 2,
                'academic_level' => 2,
                'specialization' => null,
                'course_name' => 'تحليل 2',
                'instructor_name' => 'م.شذا الخطيب',
                'day' => 'الاثنين',
                'start_time' => '12:30:00',
                'end_time' => '02:30:00',
                'room' => 'مدرج 3',
                'branch' => '1',
            ],
            [
                'semester_id' => 2,
                'academic_level' => 2,
                'specialization' => null,
                'course_name' => 'تحليل 2',
                'instructor_name' => 'م.شذا الخطيب',
                'day' => 'الاثنين',
                'start_time' => '08:30:00',
                'end_time' => '10:30:00',
                'room' => 'مدرج 3',
                'branch' => '2',
            ],
            [
                'semester_id' => 2,
                'academic_level' => 2,
                'specialization' => null,
                'course_name' => 'عملي برمجة 2',
                'instructor_name' => 'م.ميساء العبودي - م.مؤيد عالولا - م.عرين حسن - م. غالية صباغ',
                'day' => 'الاثنين',
                'start_time' => '10:30:00',
                'end_time' => '12:30:00',
                'room' => 'J1,K1,G1,H1',
                'branch' => '2',
            ],
            [
                'semester_id' => 2,
                'academic_level' => 2,
                'specialization' => null,
                'course_name' => ' جبر خطي',
                'instructor_name' => 'د.أسمهان خضور',
                'day' => 'الاثنين',
                'start_time' => '12:30:00',
                'end_time' => '02:30:00',
                'room' => 'مدرج 1',
                'branch' => '2',
            ],
            [
                'semester_id' => 2,
                'academic_level' => 2,
                'specialization' => null,
                'course_name' => ' جبر خطي',
                'instructor_name' => 'د.أسمهان خضور',
                'day' => 'الاثنين',
                'start_time' => '08:30:00',
                'end_time' => '10:30:00',
                'room' => 'مدرج 1',
                'branch' => '3',
            ],
            [
                'semester_id' => 2,
                'academic_level' => 2,
                'specialization' => null,
                'course_name' => 'تحليل 2',
                'instructor_name' => 'م.شذا الخطيب',
                'day' => 'الاثنين',
                'start_time' => '10:30:00',
                'end_time' => '12:30:00',
                'room' => 'مدرج 3',
                'branch' => '3',
            ],
            [
                'semester_id' => 2,
                'academic_level' => 2,
                'specialization' => null,
                'course_name' => 'عملي برمجة 2',
                'instructor_name' => 'م.ميساء العبودي - م.مؤيد عالولا - م.عرين حسن - م. غالية صباغ',
                'day' => 'الاثنين',
                'start_time' => '12:30:00',
                'end_time' => '02:30:00',
                'room' => 'J1,K1,G1,H1',
                'branch' => '3',
            ],

            // ///////////  4444444444/////////1111111
            [
                // // الاحد
                'semester_id' => 2,
                'academic_level' => 2,
                'specialization' => null,
                'course_name' => 'عملي تحليل 2',
                'instructor_name' => 'ق.أ. مهند بكر - م. هيام نجم الدين',
                'day' => 'الأحد',
                'start_time' => '08:30:00',
                'end_time' => '10:30:00',
                'room' => 'مدرج 22',
                'branch' => null,
            ],
            [
                'semester_id' => 2,
                'academic_level' => 4,
                'specialization' => '1',
                'course_name' => 'عملي جبر خطي',
                'instructor_name' => 'م. شذا الخطيب - م. عبير الكجك',
                'day' => 'الأحد',
                'start_time' => '12:30:00',
                'end_time' => '02:30:00',
                'room' => 'مدرج 22',
                'branch' => null,
            ],
            [
                'semester_id' => 2,
                'academic_level' => 4,
                'specialization' => '1',
                'course_name' => 'عملي جبر خطي',
                'instructor_name' => 'م. شذا الخطيب - م. عبير الكجك',
                'day' => 'الأحد',
                'start_time' => '08:30:00',
                'end_time' => '10:30:00',
                'room' => 'مدرج 21',
                'branch' => null,
            ],
            [
                'semester_id' => 2,
                'academic_level' => 4,
                'specialization' => '1',
                'course_name' => 'عملي تحليل 2',
                'instructor_name' => 'ق.أ. مهند بكر - م. هيام نجم الدين',
                'day' => 'الأحد',
                'start_time' => '10:30:00',
                'end_time' => '12:30:00',
                'room' => 'مدرج 22',
                'branch' => null,
            ],
            [
                'semester_id' => 2,
                'academic_level' => 4,
                'specialization' => '1',
                'course_name' => 'برمجة 2',
                'instructor_name' => 'د. عبد الرحمن اللحام',
                'day' => 'الأحد',
                'start_time' => '08:30:00',
                'end_time' => '10:30:00',
                'room' => 'مدرج 1',
                'branch' => null,
            ],
            [
                'semester_id' => 2,
                'academic_level' => 4,
                'specialization' => '1',
                'course_name' => 'عملي جبر خطي',
                'instructor_name' => 'م. شذا الخطيب - م. عبير الكجك',
                'day' => 'الأحد',
                'start_time' => '10:30:00',
                'end_time' => '12:30:00',
                'room' => 'مدرج 21',
                'branch' => null,
            ],
            [
                'semester_id' => 2,
                'academic_level' => 4,
                'specialization' => '1',
                'course_name' => 'عملي تحليل 2',
                'instructor_name' => 'ق.أ. مهند بكر - م. هيام نجم الدين',
                'day' => 'الأحد',
                'start_time' => '12:30:00',
                'end_time' => '02:30:00',
                'room' => 'مدرج 22',
                'branch' => null,
            ],
            // /// الاثنين
            [
                'semester_id' => 2,
                'academic_level' => 4,
                'specialization' => '1',
                'course_name' => 'عملي برمجة 2',
                'instructor_name' => 'م.ميساء العبودي - م.مؤيد عالولا - م.عرين حسن - م. غالية صباغ',
                'day' => 'الاثنين',
                'start_time' => '08:30:00',
                'end_time' => '10:30:00',
                'room' => 'J1,K1,G1,H1',
                'branch' => null,
            ],
            [
                'semester_id' => 2,
                'academic_level' => 4,
                'specialization' => '1',
                'course_name' => ' جبر خطي',
                'instructor_name' => 'د.أسمهان خضور',
                'day' => 'الاثنين',
                'start_time' => '10:30:00',
                'end_time' => '12:30:00',
                'room' => 'مدرج 1',
                'branch' => null,
            ],
            [
                'semester_id' => 2,
                'academic_level' => 4,
                'specialization' => '1',
                'course_name' => 'تحليل 2',
                'instructor_name' => 'م.شذا الخطيب',
                'day' => 'الاثنين',
                'start_time' => '12:30:00',
                'end_time' => '02:30:00',
                'room' => 'مدرج 3',
                'branch' => null,
            ],
            [
                'semester_id' => 2,
                'academic_level' => 4,
                'specialization' => '1',
                'course_name' => 'تحليل 2',
                'instructor_name' => 'م.شذا الخطيب',
                'day' => 'الاثنين',
                'start_time' => '08:30:00',
                'end_time' => '10:30:00',
                'room' => 'مدرج 3',
                'branch' => null,
            ],
            [
                'semester_id' => 2,
                'academic_level' => 4,
                'specialization' => '1',
                'course_name' => 'عملي برمجة 2',
                'instructor_name' => 'م.ميساء العبودي - م.مؤيد عالولا - م.عرين حسن - م. غالية صباغ',
                'day' => 'الاثنين',
                'start_time' => '10:30:00',
                'end_time' => '12:30:00',
                'room' => 'J1,K1,G1,H1',
                'branch' => null,
            ],
            [
                'semester_id' => 2,
                'academic_level' => 4,
                'specialization' => '1',
                'course_name' => ' جبر خطي',
                'instructor_name' => 'د.أسمهان خضور',
                'day' => 'الاثنين',
                'start_time' => '12:30:00',
                'end_time' => '02:30:00',
                'room' => 'مدرج 1',
                'branch' => null,
            ],
            [
                'semester_id' => 2,
                'academic_level' => 4,
                'specialization' => '1',
                'course_name' => ' جبر خطي',
                'instructor_name' => 'د.أسمهان خضور',
                'day' => 'الاثنين',
                'start_time' => '08:30:00',
                'end_time' => '10:30:00',
                'room' => 'مدرج 1',
                'branch' => null,
            ],
            [
                'semester_id' => 2,
                'academic_level' => 4,
                'specialization' => '1',
                'course_name' => 'تحليل 2',
                'instructor_name' => 'م.شذا الخطيب',
                'day' => 'الاثنين',
                'start_time' => '10:30:00',
                'end_time' => '12:30:00',
                'room' => 'مدرج 3',
                'branch' => null,
            ],
            [
                'semester_id' => 2,
                'academic_level' => 4,
                'specialization' => '1',
                'course_name' => 'عملي برمجة 2',
                'instructor_name' => 'م.ميساء العبودي - م.مؤيد عالولا - م.عرين حسن - م. غالية صباغ',
                'day' => 'الاثنين',
                'start_time' => '12:30:00',
                'end_time' => '02:30:00',
                'room' => 'J1,K1,G1,H1',
                'branch' => null,
            ],

            // ///////////  4444444444/////////22222
            [
                // // الاحد
                'semester_id' => 2,
                'academic_level' => 4,
                'specialization' => '2',
                'course_name' => 'عملي تحليل 2',
                'instructor_name' => 'ق.أ. مهند بكر - م. هيام نجم الدين',
                'day' => 'الأحد',
                'start_time' => '08:30:00',
                'end_time' => '10:30:00',
                'room' => 'مدرج 22',
                'branch' => null,
            ],
            [
                'semester_id' => 2,
                'academic_level' => 4,
                'specialization' => '2',
                'course_name' => 'عملي جبر خطي',
                'instructor_name' => 'م. شذا الخطيب - م. عبير الكجك',
                'day' => 'الأحد',
                'start_time' => '12:30:00',
                'end_time' => '02:30:00',
                'room' => 'مدرج 22',
                'branch' => null,
            ],
            [
                'semester_id' => 2,
                'academic_level' => 4,
                'specialization' => '2',
                'course_name' => 'عملي جبر خطي',
                'instructor_name' => 'م. شذا الخطيب - م. عبير الكجك',
                'day' => 'الأحد',
                'start_time' => '08:30:00',
                'end_time' => '10:30:00',
                'room' => 'مدرج 21',
                'branch' => null,
            ],
            [
                'semester_id' => 2,
                'academic_level' => 4,
                'specialization' => '2',
                'course_name' => 'عملي تحليل 2',
                'instructor_name' => 'ق.أ. مهند بكر - م. هيام نجم الدين',
                'day' => 'الأحد',
                'start_time' => '10:30:00',
                'end_time' => '12:30:00',
                'room' => 'مدرج 22',
                'branch' => null,
            ],
            [
                'semester_id' => 2,
                'academic_level' => 4,
                'specialization' => '2',
                'course_name' => 'برمجة 2',
                'instructor_name' => 'د. عبد الرحمن اللحام',
                'day' => 'الأحد',
                'start_time' => '08:30:00',
                'end_time' => '10:30:00',
                'room' => 'مدرج 1',
                'branch' => null,
            ],
            [
                'semester_id' => 2,
                'academic_level' => 4,
                'specialization' => '2',
                'course_name' => 'عملي جبر خطي',
                'instructor_name' => 'م. شذا الخطيب - م. عبير الكجك',
                'day' => 'الأحد',
                'start_time' => '10:30:00',
                'end_time' => '12:30:00',
                'room' => 'مدرج 21',
                'branch' => null,
            ],
            [
                'semester_id' => 2,
                'academic_level' => 4,
                'specialization' => '2',
                'course_name' => 'عملي تحليل 2',
                'instructor_name' => 'ق.أ. مهند بكر - م. هيام نجم الدين',
                'day' => 'الأحد',
                'start_time' => '12:30:00',
                'end_time' => '02:30:00',
                'room' => 'مدرج 22',
                'branch' => null,
            ],
            // /// الاثنين
            [
                'semester_id' => 2,
                'academic_level' => 4,
                'specialization' => '2',
                'course_name' => 'عملي برمجة 2',
                'instructor_name' => 'م.ميساء العبودي - م.مؤيد عالولا - م.عرين حسن - م. غالية صباغ',
                'day' => 'الاثنين',
                'start_time' => '08:30:00',
                'end_time' => '10:30:00',
                'room' => 'J1,K1,G1,H1',
                'branch' => null,
            ],
            [
                'semester_id' => 2,
                'academic_level' => 4,
                'specialization' => '2',
                'course_name' => ' جبر خطي',
                'instructor_name' => 'د.أسمهان خضور',
                'day' => 'الاثنين',
                'start_time' => '10:30:00',
                'end_time' => '12:30:00',
                'room' => 'مدرج 1',
                'branch' => null,
            ],
            [
                'semester_id' => 2,
                'academic_level' => 4,
                'specialization' => '2',
                'course_name' => 'تحليل 2',
                'instructor_name' => 'م.شذا الخطيب',
                'day' => 'الاثنين',
                'start_time' => '12:30:00',
                'end_time' => '02:30:00',
                'room' => 'مدرج 3',
                'branch' => null,
            ],
            [
                'semester_id' => 2,
                'academic_level' => 4,
                'specialization' => '2',
                'course_name' => 'تحليل 2',
                'instructor_name' => 'م.شذا الخطيب',
                'day' => 'الاثنين',
                'start_time' => '08:30:00',
                'end_time' => '10:30:00',
                'room' => 'مدرج 3',
                'branch' => null,
            ],
            [
                'semester_id' => 2,
                'academic_level' => 4,
                'specialization' => '2',
                'course_name' => 'عملي برمجة 2',
                'instructor_name' => 'م.ميساء العبودي - م.مؤيد عالولا - م.عرين حسن - م. غالية صباغ',
                'day' => 'الاثنين',
                'start_time' => '10:30:00',
                'end_time' => '12:30:00',
                'room' => 'J1,K1,G1,H1',
                'branch' => null,
            ],
            [
                'semester_id' => 2,
                'academic_level' => 4,
                'specialization' => '2',
                'course_name' => ' جبر خطي',
                'instructor_name' => 'د.أسمهان خضور',
                'day' => 'الاثنين',
                'start_time' => '12:30:00',
                'end_time' => '02:30:00',
                'room' => 'مدرج 1',
                'branch' => null,
            ],
            [
                'semester_id' => 2,
                'academic_level' => 4,
                'specialization' => '2',
                'course_name' => ' جبر خطي',
                'instructor_name' => 'د.أسمهان خضور',
                'day' => 'الاثنين',
                'start_time' => '08:30:00',
                'end_time' => '10:30:00',
                'room' => 'مدرج 1',
                'branch' => null,
            ],
            [
                'semester_id' => 2,
                'academic_level' => 4,
                'specialization' => '2',
                'course_name' => 'تحليل 2',
                'instructor_name' => 'م.شذا الخطيب',
                'day' => 'الاثنين',
                'start_time' => '10:30:00',
                'end_time' => '12:30:00',
                'room' => 'مدرج 3',
                'branch' => null,
            ],
            [
                'semester_id' => 2,
                'academic_level' => 4,
                'specialization' => '2',
                'course_name' => 'عملي برمجة 2',
                'instructor_name' => 'م.ميساء العبودي - م.مؤيد عالولا - م.عرين حسن - م. غالية صباغ',
                'day' => 'الاثنين',
                'start_time' => '12:30:00',
                'end_time' => '02:30:00',
                'room' => 'J1,K1,G1,H1',
                'branch' => null,
            ],
        ]);
    }
}
